### ISSUE TITLE
Set client name at runtime or with a project setting

### ISSUE THREAD

**Issue by MaxMustermann31** [deadpixelsociety/gspot#10]
Currently the client name is defined as a constant in gsclient.gd:
```
const CLIENT_NAME = "GSClient"
```
Would it be possible to make this accessible via the API or a project setting?

**Comment by MaxMustermann31** [comment]
In messages/gsrequest_server_info.gd you are still referencing the old constant.

```
fields[MESSAGE_FIELD_CLIENT_NAME] = GSClient.CLIENT_NAME
```

**Comment by deadpixelsociety** [comment]
> In messages/gsrequest_server_info.gd you are still referencing the old constant.
> 
> ```
> fields[MESSAGE_FIELD_CLIENT_NAME] = GSClient.CLIENT_NAME
> ```

Thanks for the catch, fixed!
