### ISSUE TITLE
Reduce clutter in client_message

### ISSUE THREAD

**Issue by MaxMustermann31** [deadpixelsociety/gspot#11]
Currently the signal `client_message` is emitted for each message send to the server. Could you split `client_message` in multiple verbosity levels so the default debug output isn't as cluttered?

**Comment by MaxMustermann31** [comment]
https://github.com/deadpixelsociety/gspot/blob/main/addons/gspot/gsclient.gd#L333
```
	_log(LogLevel.DEBUG, "Sending message: %s" % message)
```
Could this specific message be moved to a higher verbosity level than everything else? This is basically the only message I don't want to log since it is send every time the vibration level changes which can happen pretty often and is not all that useful information in normal application use.

**Comment by deadpixelsociety** [comment]
> https://github.com/deadpixelsociety/gspot/blob/main/addons/gspot/gsclient.gd#L333
> 
> ```
> 	_log(LogLevel.DEBUG, "Sending message: %s" % message)
> ```
> 
> Could this specific message be moved to a higher verbosity level than everything else? This is basically the only message I don't want to log since it is send every time the vibration level changes which can happen pretty often and is not all that useful information in normal application use.

That one I would like to keep at DEBUG level as that's it's intended use. The output of client_message is largely intended to be used for developer review of what's happening inside GSClient without needing to debug step through everything themselves. 

If you want cleaner output for yourself or going to your end users I would suggest connecting to the other signals and providing feedback based on their emissions. If any of those signals need improving or more are needed we can certainly look at that.
